apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: web-app-doppler-sync
  namespace: default
spec:
  tokenSecret:
    name: vaultwarden-doppler-token
  managedSecret:
    name: vaultwarden-secrets
    namespace: vaultwarden
