postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
  auth:
    existingSecret: "infisical-postgres-creds"
    secretKeys:
      userPasswordKey: "password"
  primary:
    persistence:
      enabled: true

redis:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
  auth:
    enabled: true
    existingSecret: "infisical-redis-creds"
    existingSecretPasswordKey: "redis-password"
  master:
    persistence:
      enabled: true
  replica:
    replicaCount: 0
